print('Hello Nastya and Nikita')
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("UuUUuUuUUuUUuUuUuuUUu")
print("YYYYYYYYYYYYYYYYYYYYY")
